# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-24 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210724_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
