# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-26 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20210725_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
